
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNMaterial3Spec.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeDatePickerSpecJSI_show(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "show", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Callback;Lcom/facebook/react/bridge/Callback;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeDatePickerSpecJSI::NativeDatePickerSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["show"] = MethodMetadata {3, __hostFunction_NativeDatePickerSpecJSI_show};
}

std::shared_ptr<TurboModule> RNMaterial3Spec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "RTNDatePicker") {
    return std::make_shared<NativeDatePickerSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
