/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  class JSI_EXPORT NativeDatePickerCxxSpecJSI : public TurboModule {
protected:
  NativeDatePickerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::Value show(jsi::Runtime &rt, jsi::Object props, jsi::Function onChange, std::optional<jsi::Function> onCancel) = 0;

};

template <typename T>
class JSI_EXPORT NativeDatePickerCxxSpec : public TurboModule {
public:
  jsi::Value get(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.get(rt, propName);
  }

  static constexpr std::string_view kModuleName = "RTNDatePicker";

protected:
  NativeDatePickerCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeDatePickerCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}


private:
  class Delegate : public NativeDatePickerCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeDatePickerCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {

    }

    jsi::Value show(jsi::Runtime &rt, jsi::Object props, jsi::Function onChange, std::optional<jsi::Function> onCancel) override {
      static_assert(
          bridging::getParameterCount(&T::show) == 4,
          "Expected show(...) to have 4 parameters");

      return bridging::callFromJs<jsi::Value>(
          rt, &T::show, jsInvoker_, instance_, std::move(props), std::move(onChange), std::move(onCancel));
    }

  private:
    friend class NativeDatePickerCxxSpec;
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
