/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNMaterial3SpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeDatePickerCxxSpecJSI_show(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDatePickerCxxSpecJSI *>(&turboModule)->show(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asObject(rt).asFunction(rt),
    count <= 2 || args[2].isUndefined() ? std::nullopt : std::make_optional(args[2].asObject(rt).asFunction(rt))
  );
}

NativeDatePickerCxxSpecJSI::NativeDatePickerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("RTNDatePicker", jsInvoker) {
  methodMap_["show"] = MethodMetadata {3, __hostFunction_NativeDatePickerCxxSpecJSI_show};
}


} // namespace facebook::react
